version: '3.8'

services:
  # Base de datos local para MISP
  misp-db:
    image: mariadb:10.4
    container_name: pmp-misp-db
    restart: always
    environment:
      MYSQL_DATABASE: misp
      MYSQL_USER: misp
      MYSQL_PASSWORD: misp_password
      MYSQL_ROOT_PASSWORD: my_root_password
    volumes:
      - misp-db-data:/var/lib/mysql

  # Redis para MISP
  misp-redis:
    image: redis:6-alpine
    container_name: pmp-misp-redis
    restart: always
    volumes:
      - misp-redis-data:/data

  # Módulos de Enriquecimiento MISP (Shodan, VirusTotal, CVEs, etc.)
  misp-modules:
    image: coolacid/misp-docker:modules-latest
    container_name: pmp-misp-modules
    platform: linux/amd64
    restart: always
    environment:
      - REDIS_BACKEND=misp-redis
    depends_on:
      - misp-redis
    ports:
      - "6666:6666"

  # El propio servidor MISP para visualizar la inteligencia (Web GUI + API)
  misp-server:
    image: coolacid/misp-docker:core-latest
    container_name: pmp-misp-server
    platform: linux/amd64
    restart: always
    depends_on:
      - misp-db
      - misp-redis
      - misp-modules
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - MYSQL_HOST=misp-db
      - MYSQL_DATABASE=misp
      - MYSQL_USER=misp
      - MYSQL_PASSWORD=misp_password
      - REDIS_FQDN=misp-redis
      - MISP_BASEURL=http://localhost:8080
      - MISP_ADMIN_EMAIL=admin@novadef.local
      - MISP_ADMIN_PASSPHRASE=admin123!
      - CRON_USER_ID=1
    volumes:
      - misp-server-data:/var/www/MISP
      - ./certs:/etc/nginx/certs

  # Nuestro módulo Integrador PMP -> MISP (espera pasivamente a Kafka)
  misp-integrator:
    build: .
    container_name: pmp-misp-integrator
    restart: on-failure
    environment:
      - MISP_URL=https://misp-server # URL interna del contenedor MISP
      - MISP_KEY=NOVADEFMISPINTEGRATIONKEYpmp1234567890ab
      - MISP_VERIFY_CERT=False
      # Conexión al Kafka de la PMP
      - KAFKA_BROKER=kafka_novadef:29092 
      - KAFKA_TOPICS=syslog_logs,systemd_logs,falco_events,telegraf_metrics,tshark_traces,snort_alerts,cic_flow
      # Conexión directa a MongoDB para correlación
      - MONGO_URI=mongodb://admin:admin123@mongodb_novadef:27017/
      # Conexión a Neo4j para extracción de perfil TAPCD
      - NEO4J_HTTP_URL=http://neo4j:7474/db/neo4j/tx/commit
      - NEO4J_USER=neo4j
      - NEO4J_PASS=neo4jpass
      # OpenSearch: métricas telegraf + syslog indexadas por Logstash
      - OPENSEARCH_URL=https://opensearch-node:9200
      - OPENSEARCH_USER=admin
      - OPENSEARCH_PASSWORD=Mp0^MKFJdRq*qipBHLKc
    depends_on:
      - misp-server

volumes:
  misp-db-data:
  misp-redis-data:
  misp-server-data:

networks:
  default:
    external: true
    name: launcher_default